name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: false

env:
  name: prafull
  sirname: garg

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.config-path }}
    - run : |
       echo "tag=${{env.name}}/${{env.sirname}} " >> $GITHUB_ENV
       echo "${{env.tag}}"
       echo "${{github.env.tag}}"
